export const theme = {
  colors: {
    primary: '#00C2B3',
    deepBlue: '#0D2B45',
    lightGray: '#F1F4F6',
    mediumGray: '#A8B1BA',
    white: '#FFFFFF',
    black: '#000000',
    dangerRed: '#E53935',
    amber: '#FFB020',
  },
  fontFamily: {
    regular: 'Inter_400Regular',
    medium: 'Inter_500Medium',
    semibold: 'Inter_600SemiBold',
    bold: 'Inter_700Bold',
  },
  fontSize: {
    xs: 12,
    sm: 14,
    md: 16,
    lg: 20,
    xl: 24,
    '2xl': 28,
    '3xl': 32,
    '4xl': 40,
    '5xl': 48,
  },
  fontWeight: {
    normal: '400' as const,
    medium: '500' as const,
    semibold: '600' as const,
    bold: '700' as const,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    '2xl': 48,
  },
  radius: {
    sm: 10,
    md: 12,
    lg: 16,
    full: 999,
  },
  dimensions: {
    buttonHeight: 52,
    buttonCTAHeight: 56,
    inputHeight: 48,
    navbarHeight: 56,
    statusBarHeight: 44,
    screenWidth: 390,
    tabBarHeight: 68,
  },
  shadows: {
    card: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 4,
    },
    button: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.04,
      shadowRadius: 5,
      elevation: 1,
    },
  },
  fontStyles: {
    heading: {
      fontSize: 32,
      fontWeight: '700' as const,
      color: '#0D2B45',
    },
    subheading: {
      fontSize: 20,
      fontWeight: '600' as const,
      color: '#0D2B45',
    },
    body: {
      fontSize: 16,
      fontWeight: '400' as const,
      color: '#0D2B45',
    },
    label: {
      fontSize: 12,
      fontWeight: '500' as const,
      color: '#A8B1BA',
      textTransform: 'uppercase' as const,
      letterSpacing: 1,
    },
    caption: {
      fontSize: 12,
      fontWeight: '400' as const,
      color: '#A8B1BA',
    },
    amount: {
      fontSize: 40,
      fontWeight: '700' as const,
      color: '#0D2B45',
    },
  },
};

export type Theme = typeof theme;
