export const theme = {
  colors: {
    turquoise: '#1BBFAE',
    deepBlue: '#0F2A44',
    lightGray: '#EDF1F5',
    mediumGray: '#8A93A0',
    white: '#FFFFFF',
    dangerRed: '#FF6B6B',
    amber: '#FFB020',
  },
  fontFamily: {
    regular: 'Nunito_400Regular',
    medium: 'Nunito_500Medium',
    semibold: 'Nunito_600SemiBold',
    bold: 'Nunito_700Bold',
  },
  fontSize: {
    xs: 12,
    sm: 14,
    md: 16,
    lg: 20,
    xl: 24,
    '2xl': 28,
    '3xl': 32,
    '4xl': 40,
    '5xl': 48,
  },
  fontWeight: {
    normal: '400' as const,
    medium: '500' as const,
    bold: '700' as const,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    '2xl': 48,
  },
  radius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    full: 9999,
    inputRadius: 8,
    pill: 24,
    buttonRadius: 12,
  },
  dimensions: {
    buttonHeight: 48,
    buttonCTAHeight: 56,
    inputHeight: 48,
    navbarHeight: 64,
    screenWidth: 375,
    tabBarHeight: 68,
  },
  fontStyles: {
    label: {
      fontSize: 12,
      fontWeight: '500' as const,
      color: '#8A93A0',
      textTransform: 'uppercase' as const,
      letterSpacing: 1,
    },
  },
};

export type Theme = typeof theme;
